-- The table that references the other must be dropped first

drop table if exists users;

create table users(
    user_id serial primary key,
    username varchar(40) not null unique,
    password text not null,
    email text not null unique
)

insert into users(username, password, email)
values
('Destiny', 'djones', 'djones5713@gmail.com');



drop table if exists destinations;

create table destinations(
    destination_id serial primary key,
    region text not null,
    country text not null,
    destination text not null,
    image_url text not null,
    description text not null
)


insert into  destinations( region, country, destination, image_url, description)
values

('North America','United States','Honolulu, Hawaii', 'https://i.imgur.com/Qsc6Siw.jpg','Beyond Honolulu,  the islands are scenic villages and beaches such as Hanauma Bay, Kailua Beach, Makaha Beach and Waimea Bay. The North Shore is a quiet, laid-back area where visitors can sample a Hawaiian plate lunch and some shave ice before hitting one of its prime surfing and snorkeling spots.')

('North America','United States','Oahu, Hawaii', 'https://i.imgur.com/3vBSB9T.jpg','Oahu is a U.S. island in the Central Pacific, part of the Hawaiian island chain and home to the state capital, Honolulu. Highlights of the city include historic Chinatown and the Punchbowl, a crater-turned-cemetery. Waikiki is an iconic beach, dining and nightlife area.')
('North America','United States', 'Kauai, Hawaii', 'https://i.imgur.com/c31oHs7.jpg','Kauai is an island in the Central Pacific, part of the Hawaiian archipelago. The dramatic cliffs and pinnacles of its Na Pali Coast have served as a backdrop for major Hollywood films, while 10-mile-long Waimea Canyon and the Nounou Trails traversing the Sleeping Giant mountain ridge are hiking destinations.')
('North America','United States', 'Lahaina, Hawaii', 'https://i.imgur.com/tG06z9p.jpg','Lahaina is the largest census-designated place (CDP) in West Maui, Maui County, Hawaii, United States and includes the Kaanapali and Kapalua beach resorts. As of the 2010 census, the CDP had a resident population of 11,704.[1] Lahaina encompasses the coast along Hawaii Route 30 from a tunnel at the south end, through Olowalu and to the CDP of Napili-Honokowai to the north.')
('North America','United States', 'Hilo, Hawaii', 'https://i.imgur.com/iUzX8Q1.jpg','Hilo is a town on Hawaii, commonly called the Big Island, in the state of Hawaii. It’s known for Wailuku River State Park, featuring Waianuenue, or Rainbow Falls, with its colorful mist effects. The bubbling basalt-lava rock pools known as the Boiling Pots are nearby. To the south is Hawaii Volcanoes National Park, home to rainforests and the active Kilauea and Mauna Loa volcanoes.')
('North America','United States', 'Maui, Hawaii', 'https://i.imgur.com/DsS09RL.jpg','Maui is an island in the Central Pacific, part of the Hawaiian archipelago. Sprawling Haleakala National Park encompasses the island’s highest peak, volcanic Haleakala, as well as the pools and waterfalls of Ohe’o Gulch, accessed via scenic, winding Hana Highway. The island is 30 miles of beaches include golden-crescent Kapalua, sheltered from strong currents by lava-rock promontories.')
('Europe','Italy','Rome','https://i.imgur.com/uOkmfpI.jpg','Rome, Italy’s capital, is a sprawling, cosmopolitan city with nearly 3,000 years of globally influential art, architecture and culture on display. Ancient ruins such as the Forum and the Colosseum evoke the power of the former Roman Empire. Vatican City, headquarters of the Roman Catholic Church, has St. Peter’s Basilica and the Vatican Museums, which house masterpieces such as Michelangelo’s Sistine Chapel frescoes.')
('Europe','Italy','Venice','https://i.imgur.com/vRt87J3.jpg','Venice, the capital of northern Italy’s Veneto region, is built on more than 100 small islands in a lagoon in the Adriatic Sea. It has no roads, just canals – including the Grand Canal thoroughfare – lined with Renaissance and Gothic palaces. The central square, Piazza San Marco, contains St. Mark’s Basilica, which is tiled with Byzantine mosaics, and the Campanile bell tower offering views of the city’s red roofs.')
('Europe','Italy','Florence','https://i.imgur.com/QvJndkJ.jpg','Florence, capital of Italy’s Tuscany region, is home to many masterpieces of Renaissance art and architecture. One of its most iconic sights is the Duomo, a cathedral with a terracotta-tiled dome engineered by Brunelleschi and a bell tower by Giotto. The Galleria dellAccademia displays Michelangelo’s “David” sculpture.')
('Europe','Italy','Milan','https://i.imgur.com/93TxFeX.jpg','Milan, a metropolis in Italy is northern Lombardy region, is a global capital of fashion and design. Home to the national stock exchange, it’s a financial hub also known for its high-end restaurants and shops. The Gothic Duomo di Milano cathedral and the Santa Maria delle Grazie convent, housing Leonardo da Vinci’s mural “The Last Supper,” testify to centuries of art and culture.')
('Europe','Italy','Naples','https://i.imgur.com/gf3eSXT.jpg','Naples, a city in southern Italy, sits on the Bay of Naples. Nearby is Mount Vesuvius, the still-active volcano that destroyed nearby Roman town Pompeii. Dating to the 2nd millennium B.C., Naples has centuries of important art and architecture. The city has a cathedral, the Duomo di San Gennaro, is filled with frescoes. Other major landmarks include the lavish Royal Palace and Castel Nuovo, a 13th-century castle.')
('Asia','India', 'Mumbia','https://i.imgur.com/Z3HkZUn.jpg','Mumbai (formerly called Bombay) is a densely populated city on India’s west coast. A financial center, it is the largest city in India. On the Mumbai Harbour waterfront stands the iconic Gateway of India stone arch, built by the British Raj in 1924. Offshore, nearby Elephanta Island holds ancient cave temples dedicated to the Hindu god Shiva. The city is also famous as the heart of the Bollywood film industry.')
('Asia','India', 'New Delhi','https://i.imgur.com/fN9tpFx.jpg','New Delhi is an urban district of Delhi which serves as the capital of India and seat of all three branches of the Government of India. The foundation stone of the city was laid by Emperor George V during the Delhi Durbar of 1911. It was designed by British architects, Sir Edwin Lutyens and Sir Herbert Baker. ')
('Asia','India', 'Goa','https://i.imgur.com/p4yRtET.jpg','Goa is a state in western India with coastlines stretching along the Arabian Sea. Its long history as a Portuguese colony prior to 1961 is evident in its preserved 17th-century churches and the area’s tropical spice plantations. Goa is also known for its beaches, ranging from popular stretches at Baga and Palolem to those in laid-back fishing villages such as Agonda.')
('Asia','India', 'Kolkata','https://i.imgur.com/NdxzKvu.jpg','Founded as an East India Company trading post, it was the capital of India under the British Raj from 1773–1911. Today it’s known for its grand colonial architecture, art galleries and cultural festivals. It’s also home to Mother House, headquarters of the Missionaries of Charity, founded by Mother Teresa, whose tomb is on site.')
('Asia','India', 'Jodhpur','https://i.imgur.com/rwAhViF.jpg','Jodhpur is a city in the Thar Desert of the northwest Indian state of Rajasthan. Its 15th-century Mehrangarh Fort is a former palace that’s now a museum, displaying weapons, paintings and elaborate royal palanquins (sedan chairs). Set on on a rocky outcrop, the fort overlooks the walled city, where many buildings are painted the city’s iconic shade of blue.')
('Asia','Philippines', 'Bohol','https://i.imgur.com/STWmZUP.jpg','Bohol is a province of the Philippines, in the country’s Central Visayas region. It comprises Bohol Island and numerous smaller surrounding islands. Bohol is known for coral reefs and unusual geological formations, notably the Chocolate Hills.')
('Asia','Philippines', 'Puerto Princesa','https://i.imgur.com/vRiurS5.jpg','Puerto Princesa is a coastal city on Palawan Island in the western Philippines. It is a base for boat trips through the massive limestone caves and underground river of the biodiverse Puerto Princesa Subterranean River National Park.')
('Asia','Philippines', 'Coron','https://i.imgur.com/TCLKK0D.jpg','Coron, officially the Municipality of Coron is a 1st class municipality in the province of Palawan, Philippines. According to the 2015 census, it has a population of 51,803 people. It comprises the eastern half of Busuanga Island, all of Coron Island and about 50 other minor islets stretching as far as Tara Island in the north-east and Canipo Island in the south.')
('Asia','Philippines', 'Cebu','https://i.imgur.com/6KoQS6d.jpg','Cebu is a province of the Philippines, in the country’s Central Visayas region, comprising Cebu Island and more than 150 smaller surrounding islands and islets. Its prosperous port capital, Cebu City, retains landmarks from its 16th-century Spanish colonial past, including the Basilica Minore del Santo Niño church and triangular Fort San Pedro.')
('Asia','Philippines', 'Palawan','https://i.imgur.com/Hhwc0GG.jpg','Palawan, officially the Province of Palawan is an archipelagic province of the Philippines that is located in the region of MIMAROPA. It is the largest province in the country in terms of total area of jurisdiction. Its capital is the city of Puerto Princesa, but the city is governed independently from the province as a highly urbanized city.')
('Africa','Egypt', 'Cairo','https://i.imgur.com/q784ya9.jpg','Cairo, Egypt’s sprawling capital, is set on the Nile River. At its heart is Tahrir Square and the vast Egyptian Museum, a trove of antiquities including royal mummies and gilded King Tutankhamun artifacts. Nearby, Giza is the site of the iconic pyramids and Great Sphinx, dating to the 26th century BC. In Gezira Island’s leafy Zamalek district, 187m Cairo Tower affords panoramic city views.')
('Africa','South Africa', 'Cape Town','https://i.imgur.com/mLkz12p.jpg','Cape Town is a port city on South Africa’s southwest coast, on a peninsula beneath the imposing Table Mountain. Slowly rotating cable cars climb to the mountain’s flat top, from which there are sweeping views of the city, the busy harbor and boats heading for Robben Island, the notorious prison that once held Nelson Mandela, which is now a living museum.')
('Africa','Madagascar','The Avenue of the Baobabs','https://i.imgur.com/xpmrAxi.jpg','The Avenue of the Baobabs, or Alley of the Baobabs, is a prominent group of Grandidier baobabs lining the dirt road between Morondava and Beloni Tsiribihina in the Menabe region of western Madagascar.')
('Africa','Tanzanian', 'Unguja','https://i.imgur.com/OvquthB.jpg','Unguja, also known as Zanzibar Island, is the main island in the Tanzanian archipelago of Zanzibar. Stone Town, part of Zanzibar City, is an old trade center, with mosques and winding lanes. The 1883 House of Wonders is a former sultan’s palace with a clock tower. The Old Fort now houses a cultural center and a stone amphitheater.')
('Africa','Morocco', 'Chefchaouen','https://i.imgur.com/p6ZoENW.jpg','Chefchaouen, or Chaouen, is a city in the Rif Mountains of northwest Morocco. It’s known for the striking, blue-washed buildings of its old town. Leather and weaving workshops line its steep cobbled lanes. In the shady main square of Place Outa el Hammam is the red-walled Kasbah, a 15th-century fortress and dungeon, and Chefchouen Ethnographic Museum. The octagonal minaret of the Great Mosque rises nearby.')
('Asia','China', 'Beijing','https://i.imgur.com/CW6oKKb.jpg','Beijing, China’s sprawling capital, has history stretching back 3 millennia. Yet it’s known as much for modern architecture as its ancient sites such as the grand Forbidden City complex, the imperial palace during the Ming and Qing dynasties. Nearby, the massive Tiananmen Square pedestrian plaza is the site of Mao Zedong’s mausoleum and the National Museum of China, displaying a vast collection of cultural relics.')
('Asia','China', 'Shanghai','https://i.imgur.com/RphCoKA.jpg','Shanghai, on China’s central coast, is the biggest city in China and a global financial hub. Its heart is the Bund, a famed waterfront promenade lined with colonial-era buildings. Across the Huangpu River rises the Pudong district’s futuristic skyline, including 632m Shanghai Tower and the Oriental Pearl TV Tower, with distinctive pink spheres. Sprawling Yu Garden has traditional pavilions, towers and ponds.')
('Asia','China', 'Xian','https://i.imgur.com/bdhQwaq.jpg','Xi’an is a large city and capital of Shaanxi Province in central China. Once known as Chang’an (Eternal Peace), it marks the Silk Road’s eastern end and was home to the Zhou, Qin, Han and Tang dynasties ruling houses. At archaeological sites in Xi’an’s surrounding plains are the famed Bingmayong (Terra Cotta Army), thousands of life-size, hand-molded figures buried with China’s first emperor, Qin Shi Huang.')
('Asia','China', 'Hangzhou','https://i.imgur.com/HHlbEga.jpg','Hangzhou, the capital of China’s Zhejiang province, is the southern terminus of the ancient Grand Canal waterway, which originates in Beijing. Its West Lake, celebrated by poets and artists since the 9th century, encompasses islands (reachable by boat), temples, pavilions, gardens and arched bridges. On its south bank is 5-story Leifeng Pagoda, a modern reconstruction of a structure built in 975 A.D.')
('Asia','China', 'Qingdao','https://i.imgur.com/Vbguc2P.jpg','Qingdao, in China’s eastern Shandong province, is a port city of skyscrapers, parks and beaches bordering the Yellow Sea. It is known for its beer, a legacy of the German occupation (1898-1914). The Tsingtao Beer Museum celebrates the namesake brewery, founded here by Germans in 1903, and the Qingdao International Beer Festival is major event. There is also German-style architecture in the old city center.')
('Africa','United Arab Emirates', 'Dubai','https://i.imgur.com/JDeZJWB.jpg','Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture and a lively nightlife scene. Burj Khalifa, an 830m-tall tower, dominates the skyscraper-filled skyline. At its foot lies Dubai Fountain, with jets and lights choreographed to music. On artificial islands just offshore is Atlantis, The Palm, a resort with water and marine-animal parks.')
('Africa','Middle East', 'Jerusalem','https://i.imgur.com/J826GTR.jpg','Jerusalem is a city in the Middle East, located on a plateau in the Judaean Mountains between the Mediterranean and the Dead Sea. It is one of the oldest cities in the world, and is considered holy to the three major Abrahamic religions—Judaism, Christianity, and Islam.')
('North America','United States','Arizona','https://i.imgur.com/vOoDTHh.jpg','Arizona, a southwestern U.S. state, is best known for the Grand Canyon, the mile-deep chasm carved by the Colorado River. Flagstaff, a ponderosa pine–covered mountain town, is a major gateway to the Grand Canyon. Other natural sites include Saguaro National Park, protecting cactus-filled Sonoran Desert landscape. Tucson is University of Arizona territory and home to the Arizona-Sonora Desert Museum.')
('Africa','Egypt','Hurghada','https://i.imgur.com/mGQVkIy.jpg','Hurghada is a beach resort town stretching some 40km along Egypt’s Red Sea coast. It’s renowned for scuba diving, and has numerous dive shops and schools in its modern Sekalla district. There are many restaurants, bars and nightclubs, while the old town, El Dahar, is home to traditional Egyptian coffee shops and souks. Hurghada’s long stretch of sandy beach is lined with resort hotels.')
('Asia','Turkey','Bodrum','https://i.imgur.com/4QVvsnC.jpg','Bodrum is a city on the Bodrum Peninsula, stretching from Turkey southwest coast into the Aegean Sea. The city features twin bays with views of Bodrum Castle. This medieval fortress was built partly with stones from the Mausoleum at Halicarnassus, one of the Seven Wonders of the Ancient World, completed in the 4th century B.C. The city is also a gateway for nearby beach towns and resorts.')
('South America','Peru','Machu Picchu','https://i.imgur.com/uXPdP7q.jpg','Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments and panoramic views. Its exact former use remains a mystery.')
('South America','Peru','Lima','https://i.imgur.com/uXPdP7q.jpg','Lima, the capital of Peru, lies on the arid Pacific coast. Though its colonial center is preserved, it is a bustling metropolis and one of South America’s largest cities. It is home to the Museo Larco collection of pre-Columbian art and the Museo de la Nación, tracing the history of Peru’s ancient civilizations. The Plaza de Armas and the 16th-century cathedral are the heart of old Lima Centro.')
('South America','Brazil','Rico de Janerio','https://i.imgur.com/xbaaqqQ.jpg',' Rio de Janeiro is a huge seaside city in Brazil, famed for its Copacabana and Ipanema beaches, 38m Christ the Redeemer statue atop Mount Corcovado and for Sugarloaf Mountain, a granite peak with cable cars to its summit. The city is also known for its sprawling favelas (shanty towns). Its raucous Carnaval festival, featuring parade floats, flamboyant costumes and samba dancers, is considered the world’s largest.')
('South America','Bolivia','Isla del Sol','https://i.imgur.com/rWRWeGY.jpg','Isla del Sol is a Bolivian island in Lake Titicaca. It’s crossed by trails and known for Inca sites like Pilko Kaina, with its ruined palace. In nearby Yumani village, the Escalera del Inca is a staircase leading to a spring once believed to prolong youth. In the north, near Challapampa village, are the labyrinth-like Chincana ruins. The Roca Sagrada is a large rock said to be the birthplace of the first Incas.')
('South America','Chile','Easter Island','https://i.imgur.com/PMAVfYQ.jpg','Easter Island, a Chilean territory, is a remote volcanic island in Polynesia. Its native name is Rapa Nui. It’s famed for archaeological sites, including nearly 900 monumental statues called moai, created by inhabitants during the 13th–16th centuries. The moai are carved human figures with oversize heads, often resting on massive stone pedestals called ahus.')
('North America','Costa Rica','Arenal Volcano','https://imgur.com/6m4GdZn','Arenal Volcano is a dormant andesitic stratovolcano in north-western Costa Rica around 90 km northwest of San José, in the province of Alajuela, canton of San Carlos, and district of La Fortuna. The Arenal volcano measures at least 1,633 metres high. It is conically shaped with a crater 140 metres in diameter.')
('North America','Belize','Xunantunich','https://i.imgur.com/trSMYN9.jpg','Xunantunich is an Ancient Maya archaeological site in western Belize, about 70 miles west of Belize City, in the Cayo District. Xunantunich is located atop a ridge above the Mopan River, well within sight of the Guatemala border – which is a mere 0.6 miles to the west.')
('North America','Panama','San Blas Islands','https://i.imgur.com/7lDznkK.jpg','The San Blas Islands of Panama is an archipelago comprising approximately 365 islands and cays, of which 49 are inhabited. They lie off the north coast of the Isthmus of Panama, east of the Panama Canal. A part of the comarca Guna Yala along the Caribbean coast of Panama is home to the Guna people')
('North America','Guatemala','Tikal','https://i.imgur.com/bGufXGZ.jpg','Tikal is an ancient Mayan citadel in the rainforests of northern Guatemala. Possibly dating to the 1st century A.D., Tikal flourished between 200 and 850 A.D. and was later abandoned. Its iconic ruins of temples and palaces include the giant, ceremonial Lost World (Mundo Perdido) Pyramid and the Temple of the Grand Jaguar. At 70 meters, Temple IV is the tallest pre-Columbian structure in the Americas.')
('North America','Honduras','Cayos Cochinos','https://i.imgur.com/diuxV5v.jpg','The Cayos Cochinos or Cochinos Cays consist of two small islands and 13 more small coral cays situated 30 kilometres northeast of La Ceiba on the northern shores of Honduras. Although geographically separate, they belong to the Bay Islands department and are part of Roatán municipality.')
('North America','Haiti','Tortuga','https://i.imgur.com/0Jk9D0G.jpg','Tortuga is a rocky, mountainous island in Haiti, just off the northern coast of the mainland. The fishing port of Basse-Terre, on the island’s south coast, is home to the ruined 17th-century Fort de Rocher, once a pirate stronghold. In the east, one of the island’s caves, Grotte au Bassin, has a large pre-Columbian sculpture of a woman. Beaches include Pointe Ouest, at the western tip, with wide white sands.')
('North America','Dominican Republic','Los Haitises National Park','https://i.imgur.com/9s9iczk.jpg','Los Haitises National Park is a national park located on the remote northeast coast of the Dominican Republic that was established in 1976. It consists of a limestone karst plateau with conical hills, sinkholes and caverns, and there is a large area of mangrove forest on the coast.')
('North America','United States','Saint Thomas','https://i.imgur.com/qnjlqNc.jpg','St. Thomas is the gateway isle of the U.S. Virgin Islands in the Caribbean. It is known for its beaches and snorkeling spots. Territorial capital Charlotte Amalie, founded by the Danish in the 1600s, is a busy cruise-ship port. Historic buildings include a 1679 watchtower called Blackbeard’s Castle, in reference to the area’s pirate history. On the harbor, 17th-century Fort Christian is now a local-history museum.')
('North America','Cuba','Viñales Valley','https://i.imgur.com/c1Lbjpe.jpg','Viñales Valley is a karstic depression in Cuba. The valley has an area of 132 km² and is located in the Sierra de los Órganos mountains, just north of Viñales in the Pinar del Río Province')